from django.urls import path, re_path
from .views import (
    proxy_request,
    staff_notification_create,
    home_page,
    products_page,
    product_detail_page,
    wishlist_page,
    notifications_page,
    orders_page,
    order_tracking_page,
    reviews_page,
    shipping_tracking_page,
    chatbot_page,
    search_page,
    profile_page,
    checkout_page,
    cart_page,
    login_page,
    register_page,
    staff_dashboard_page,
    staff_orders_page,
    staff_shipping_page,
    staff_reviews_page,
    staff_notifications_page,
    admin_dashboard_page,
    admin_users_page,
    admin_catalog_page,
    admin_orders_page,
    admin_reviews_page,
    admin_notifications_page,
    admin_ai_page,
)

urlpatterns = [
    # HTML Pages
    path('', home_page, name='home'),
    path('home/', home_page, name='home_page'),
    path('products/', products_page, name='products'),
    path('products/<int:product_id>/', product_detail_page, name='product_detail'),
    path('wishlist/', wishlist_page, name='wishlist'),
    path('notifications/', notifications_page, name='notifications'),
    path('orders/', orders_page, name='orders'),
    path('orders/<int:order_id>/tracking/', order_tracking_page, name='order_tracking'),
    path('reviews/', reviews_page, name='reviews'),
    path('shipping/<int:order_id>/tracking/', shipping_tracking_page, name='shipping_tracking'),
    path('chatbot/', chatbot_page, name='chatbot'),
    path('search/', search_page, name='search'),
    path('profile/', profile_page, name='profile'),
    path('checkout/', checkout_page, name='checkout'),
    path('cart/', cart_page, name='cart'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('staff/', staff_dashboard_page, name='staff_dashboard'),
    path('staff/orders/', staff_orders_page, name='staff_orders'),
    path('staff/shipping/', staff_shipping_page, name='staff_shipping'),
    path('staff/reviews/', staff_reviews_page, name='staff_reviews'),
    path('staff/notifications/', staff_notifications_page, name='staff_notifications'),
    path('manager/', admin_dashboard_page, name='admin_dashboard'),
    path('manager/users/', admin_users_page, name='admin_users'),
    path('manager/catalog/', admin_catalog_page, name='admin_catalog'),
    path('manager/orders/', admin_orders_page, name='admin_orders'),
    path('manager/reviews/', admin_reviews_page, name='admin_reviews'),
    path('manager/notifications/', admin_notifications_page, name='admin_notifications'),
    path('manager/ai/', admin_ai_page, name='admin_ai'),
    path('api/notifications/create/', staff_notification_create, name='staff_notification_create'),
    
    # Legacy pages (for compatibility)
    path('customer-login/', home_page),
    path('books/', home_page),
    path('cart-page/', cart_page),
    path('checkout-page/', checkout_page),
    path('dashboard/', home_page),
    
    # API Proxy routes
    re_path(r'^(?P<path>.*)$', proxy_request, name='proxy'),
]
