PRODUCT_TYPES = [
    {'slug': 'book', 'name': 'Book', 'icon': '📚'},
    {'slug': 'laptop', 'name': 'Laptop', 'icon': '💻'},
    {'slug': 'mobile', 'name': 'Mobile', 'icon': '📱'},
    {'slug': 'tablet', 'name': 'Tablet', 'icon': '📟'},
    {'slug': 'headphone', 'name': 'Headphone', 'icon': '🎧'},
    {'slug': 'monitor', 'name': 'Monitor', 'icon': '🖥️'},
    {'slug': 'keyboard', 'name': 'Keyboard', 'icon': '⌨️'},
    {'slug': 'smartwatch', 'name': 'Smartwatch', 'icon': '⌚'},
    {'slug': 'camera', 'name': 'Camera', 'icon': '📷'},
    {'slug': 'console', 'name': 'Console', 'icon': '🎮'},
    {'slug': 'mouse', 'name': 'Mouse', 'icon': '🖱️'},
    {'slug': 'speaker', 'name': 'Speaker', 'icon': '🔊'},
    {'slug': 'printer', 'name': 'Printer', 'icon': '🖨️'},
    {'slug': 'router', 'name': 'Router', 'icon': '📡'},
    {'slug': 'storage', 'name': 'Storage', 'icon': '💾'},
    {'slug': 'webcam', 'name': 'Webcam', 'icon': '📹'},
    {'slug': 'smart-home', 'name': 'Smart Home', 'icon': '🏠'},
]

BRANDS = [
    {'slug': 'penguin', 'name': 'Penguin', 'country': 'UK'},
    {'slug': 'apple', 'name': 'Apple', 'country': 'USA'},
    {'slug': 'samsung', 'name': 'Samsung', 'country': 'Korea'},
    {'slug': 'sony', 'name': 'Sony', 'country': 'Japan'},
    {'slug': 'logitech', 'name': 'Logitech', 'country': 'Switzerland'},
    {'slug': 'asus', 'name': 'ASUS', 'country': 'Taiwan'},
    {'slug': 'lenovo', 'name': 'Lenovo', 'country': 'China'},
    {'slug': 'jbl', 'name': 'JBL', 'country': 'USA'},
    {'slug': 'canon', 'name': 'Canon', 'country': 'Japan'},
    {'slug': 'tp-link', 'name': 'TP-Link', 'country': 'China'},
    {'slug': 'western-digital', 'name': 'Western Digital', 'country': 'USA'},
    {'slug': 'microsoft', 'name': 'Microsoft', 'country': 'USA'},
    {'slug': 'hp', 'name': 'HP', 'country': 'USA'},
]

PRODUCTS = [
    {'slug': 'clean-code', 'name': 'Clean Code', 'author': 'Robert C. Martin', 'type': 'book', 'category': 'reading', 'brand': 'penguin', 'price': '359000', 'stock': 42, 'description': 'A practical guide to writing cleaner software.', 'cover_image_url': 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=1200&q=80', 'attributes': {'pages': 464, 'language': 'EN'}},
    {'slug': 'macbook-pro-14', 'name': 'MacBook Pro 14', 'author': '', 'type': 'laptop', 'category': 'electronics', 'brand': 'apple', 'price': '49990000', 'stock': 12, 'description': 'Laptop hiệu năng cao cho công việc sáng tạo.', 'cover_image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80', 'attributes': {'ram': '16GB', 'storage': '512GB'}},
    {'slug': 'iphone-15', 'name': 'iPhone 15', 'author': '', 'type': 'mobile', 'category': 'electronics', 'brand': 'apple', 'price': '26990000', 'stock': 20, 'description': 'Điện thoại flagship cho trải nghiệm cao cấp.', 'cover_image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80', 'attributes': {'storage': '256GB', 'color': 'Black'}},
    {'slug': 'galaxy-tab-s9', 'name': 'Galaxy Tab S9', 'author': '', 'type': 'tablet', 'category': 'electronics', 'brand': 'samsung', 'price': '18990000', 'stock': 18, 'description': 'Máy tính bảng đa năng cho học tập và giải trí.', 'cover_image_url': 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80', 'attributes': {'display': '11-inch', 'pen': True}},
    {'slug': 'sony-wh-1000xm5', 'name': 'Sony WH-1000XM5', 'author': '', 'type': 'headphone', 'category': 'audio', 'brand': 'sony', 'price': '8990000', 'stock': 25, 'description': 'Tai nghe chống ồn chủ động hàng đầu.', 'cover_image_url': 'https://images.unsplash.com/photo-1518441902117-f0b5f8f0e2f7?auto=format&fit=crop&w=1200&q=80', 'attributes': {'wireless': True, 'battery': '30h'}},
    {'slug': 'asus-proart-monitor', 'name': 'ASUS ProArt Monitor', 'author': '', 'type': 'monitor', 'category': 'office', 'brand': 'asus', 'price': '15990000', 'stock': 9, 'description': 'Màn hình cho sáng tạo nội dung và thiết kế.', 'cover_image_url': 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'attributes': {'size': '27-inch', 'resolution': '4K'}},
    {'slug': 'logitech-mx-keys', 'name': 'Logitech MX Keys', 'author': '', 'type': 'keyboard', 'category': 'office', 'brand': 'logitech', 'price': '2890000', 'stock': 30, 'description': 'Bàn phím không dây cho năng suất cao.', 'cover_image_url': 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?auto=format&fit=crop&w=1200&q=80', 'attributes': {'layout': 'VN', 'wireless': True}},
    {'slug': 'galaxy-watch', 'name': 'Galaxy Watch6', 'author': '', 'type': 'smartwatch', 'category': 'electronics', 'brand': 'samsung', 'price': '7890000', 'stock': 14, 'description': 'Đồng hồ thông minh theo dõi sức khỏe.', 'cover_image_url': 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=1200&q=80', 'attributes': {'strap': 'Hybrid', 'waterproof': True}},
    {'slug': 'sony-alpha-a7', 'name': 'Sony Alpha A7 IV', 'author': '', 'type': 'camera', 'category': 'electronics', 'brand': 'sony', 'price': '55990000', 'stock': 7, 'description': 'Máy ảnh full-frame cho nhiếp ảnh chuyên nghiệp.', 'cover_image_url': 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80', 'attributes': {'sensor': 'Full Frame', 'video': '4K'}},
    {'slug': 'playstation-5', 'name': 'PlayStation 5', 'author': '', 'type': 'console', 'category': 'gaming', 'brand': 'sony', 'price': '13990000', 'stock': 11, 'description': 'Máy chơi game thế hệ mới.', 'cover_image_url': 'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=1200&q=80', 'attributes': {'storage': '1TB', 'controller': 'DualSense'}},
    {'slug': 'mx-master-3s', 'name': 'Logitech MX Master 3S', 'author': '', 'type': 'mouse', 'category': 'productivity', 'brand': 'logitech', 'price': '2690000', 'stock': 24, 'description': 'Chuột cao cấp tối ưu cho dân văn phòng và sáng tạo.', 'cover_image_url': 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80', 'attributes': {'dpi': '8000', 'wireless': True}},
    {'slug': 'jbl-flip-6', 'name': 'JBL Flip 6', 'author': '', 'type': 'speaker', 'category': 'audio', 'brand': 'jbl', 'price': '2790000', 'stock': 31, 'description': 'Loa Bluetooth nhỏ gọn, bass mạnh, pin bền.', 'cover_image_url': 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80', 'attributes': {'bluetooth': True, 'battery': '12h'}},
    {'slug': 'hp-laserjet-pro', 'name': 'HP LaserJet Pro', 'author': '', 'type': 'printer', 'category': 'office', 'brand': 'hp', 'price': '4590000', 'stock': 15, 'description': 'Máy in laser cho văn phòng nhỏ và vừa.', 'cover_image_url': 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80', 'attributes': {'print_speed': '30ppm', 'duplex': True}},
    {'slug': 'tp-link-ax55', 'name': 'TP-Link Archer AX55', 'author': '', 'type': 'router', 'category': 'network', 'brand': 'tp-link', 'price': '2190000', 'stock': 20, 'description': 'Router Wi-Fi 6 cho gia đình và văn phòng.', 'cover_image_url': 'https://images.unsplash.com/photo-1517420879524-86d64ac2f339?auto=format&fit=crop&w=1200&q=80', 'attributes': {'wifi': 'Wi-Fi 6', 'band': 'Dual-band'}},
    {'slug': 'wd-black-ssd-2tb', 'name': 'WD Black SN850X 2TB', 'author': '', 'type': 'storage', 'category': 'productivity', 'brand': 'western-digital', 'price': '3890000', 'stock': 28, 'description': 'SSD tốc độ cao cho game thủ và creator.', 'cover_image_url': 'https://images.unsplash.com/photo-1555617766-c94804975da6?auto=format&fit=crop&w=1200&q=80', 'attributes': {'capacity': '2TB', 'interface': 'NVMe'}},
    {'slug': 'microsoft-surface-webcam', 'name': 'Microsoft Modern Webcam', 'author': '', 'type': 'webcam', 'category': 'productivity', 'brand': 'microsoft', 'price': '1890000', 'stock': 26, 'description': 'Webcam cho họp trực tuyến và dạy học từ xa.', 'cover_image_url': 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=1200&q=80', 'attributes': {'resolution': '1080p', 'mic': True}},
    {'slug': 'canon-eos-r50', 'name': 'Canon EOS R50', 'author': '', 'type': 'camera', 'category': 'photography', 'brand': 'canon', 'price': '22990000', 'stock': 10, 'description': 'Máy ảnh mirrorless nhẹ, phù hợp vlogger và du lịch.', 'cover_image_url': 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80', 'attributes': {'sensor': 'APS-C', 'video': '4K'}},
    {'slug': 'ring-smart-light', 'name': 'Smart Light Hub', 'author': '', 'type': 'smart-home', 'category': 'smart-home', 'brand': 'samsung', 'price': '1590000', 'stock': 17, 'description': 'Thiết bị trung tâm điều khiển đèn và cảm biến thông minh.', 'cover_image_url': 'https://images.unsplash.com/photo-1518766335845-3d9b9f0b79d0?auto=format&fit=crop&w=1200&q=80', 'attributes': {'connectivity': 'Wi-Fi', 'voice_control': True}},
]
