# Generated by Django 5.2.12 on 2026-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customerproductinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerBookInteraction',
        ),
        migrations.AlterField(
            model_name='customerproductinteraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
