CREATE DATABASE IF NOT EXISTS ecommerce_auth;
CREATE DATABASE IF NOT EXISTS ecommerce_customer;
CREATE DATABASE IF NOT EXISTS ecommerce_order;
CREATE DATABASE IF NOT EXISTS ecommerce_pay;
CREATE DATABASE IF NOT EXISTS ecommerce_ship;
CREATE DATABASE IF NOT EXISTS ecommerce_staff;
CREATE DATABASE IF NOT EXISTS ecommerce_manager;
